#!/bin/sh
#
# distclean Miroslav Zagorac <mzagorac@haproxy.com>
#
test -f Makefile && make maintainer-clean

rm -rf autom4te.cache config autoscan.log configure.scan aclocal.m4 configure
rm -f Makefile.in src/Makefile.in _* config.log
rm -f src/.source-md5sums
